import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Blogcards from '../components/Blogcards'
import Tourcards from '../components/Tourcards'
import Navbar from '../components/Navbar'
import Header from '../components/Header'
import Service from '../components/Service'
import Feature from '../components/Feature'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
      <Navbar />
      <Header/>
      <Service/>
      <Feature/>
      <Blogcards />
      <Tourcards />
    </>
  )
}
